### ISSUE TITLE
Using AP-1512HH in Poland

### ISSUE THREAD

**Issue by eraytuncyilmaz** [device-teardowns/coway-ap1512hh#6]
Thank you for the detailed teardown. I live in Poland where wall sockets supply 240V / 50Hz. As I understand, to be able to use it, I need a step-down transformer with a frequency converter from **240V/50Hz** to **110V/60Hz**. 

Would it be okay to use the device without a frequency conversion? So, from  240V/50Hz to 110V/**50Hz**

Here is a post with a similar question:
https://electronics.stackexchange.com/questions/417680/converting-220v-50hz-to-110v-60hz

I couldn't find if the motor Nidec SIC-41CVJ-B543-1 would work with 50Hz. I am not sure if my device has the same motor, I didn't open it.

**Comment by larryqiann** [comment]
Hi and thank you for your comments

The motor in this device operates on DC so the frequency should not affect it. From a technical standpoint, the only problem with using it on 50 Hz is that the dc voltage may sag slightly more than on 60 Hz due to how the time between peaks is longer, during which the filter capacitor will need to carry this load. I think that this should not be a significant problem. Operating the fan at high speed with no filter installed will be the "worst case" scenario for this - at low speed and/or with filters fitted, the current is low enough to have minimal impact. 

I think that the power supply of the device is already designed to operate on 50 Hz (e.g. the main PCB has options printed on for UL/CE, KR, and CN, where CE refers likely to the EU standards which would be 50 Hz). Likely, in the EU, the power supply board remains the same, but the motor is fitted with a 310 V DC motor instead of a 170 V DC motor to accommodate the higher voltage. I would think that as long as the voltage is the same, the device would continue to function correctly. This particular device doesn't have any way for the mainboard to read the AC frequency either, so there should be no effect on the timer function. 

Hope this helps!

**Comment by eraytuncyilmaz** [comment]
Thank you for the fast reply. 

What about the maximum power consumption of the device? In the specs, power consumption is given as 77W but is this the max? Can I get away with using a 100W voltage converter?

**Comment by larryqiann** [comment]
I don't remember the exact numbers but under normal usage the device never exceeds 80W. If you operate it at high speed with the filters removed, and/or the motor gets stuck, it may use more, but this is probably not super likely. The only thing to be aware of is whether the 100W transformer is rated for 100W continuously or intermittently, but as I mentioned, the average power consumption of the device is significantly lower and is closer to 20-50W, or only 10W or less on low.
